baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Strata"
theme = "hugo-strata-theme"

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Your name"
	description = "Describe your website"

	# Enable Google Analytics by inserting your tracking code
	googleAnalytics = ""


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**I'm Strata**, a super simple<br> responsive site template freebie<br> crafted by [HTML5 UP](//html5up.net)."
		# The icons will be shown if you enter your username
		twitter = "spf13"
		github = "spf13"
		dribbble = ""
		facebook = ""

		copyright = [
			"&copy; John Doe",
			"Design: [HTML5 UP](//html5up.net)",
			"Demo Images: [Unsplash](//unsplash.com/)"
		]


	[params.about]
		title = "Ipsum lorem dolor aliquam ante commodo magna sed accumsan arcu neque."
		content = "Accumsan orci faucibus id eu lorem semper. Eu ac iaculis ac nunc nisi lorem vulputate lorem neque cubilia ac in adipiscing in curae lobortis tortor primis integer massa adipiscing id nisi accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque cubilia."


	[params.portfolio]
		title = "Recent Work"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/01.jpg"
			thumb = "thumbs/01.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/03.jpg"
			thumb = "thumbs/03.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/04.jpg"
			thumb = "thumbs/04.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/05.jpg"
			thumb = "thumbs/05.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/06.jpg"
			thumb = "thumbs/06.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."


	[params.contact]
		title = "Get In Touch"
		content = "Accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque lorem ipsum dolor."

		address = [
			"1234 Somewhere Rd.",
			"Nashville, TN 00000",
			"United States"
		]
		phone = "000-000-0000"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "hello@example.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"